name: Build XMCL Flatpak

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.latest-release.outputs.version }}
      original_url: ${{ steps.latest-release.outputs.original_url }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Flatpak
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder
          flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

      - name: Get latest XMCL release
        id: latest-release
        run: |
          RELEASE_INFO=$(curl -s https://api.github.com/repos/Voxelum/x-minecraft-launcher/releases/latest)
          VERSION=$(echo $RELEASE_INFO | jq -r '.tag_name' | sed 's/^v//')
          ORIGINAL_URL=$(echo $RELEASE_INFO | jq -r '.html_url')
          TARXZ_URL=$(echo $RELEASE_INFO | jq -r '.assets[] | select(.name | endswith("-x64.tar.xz")) | .browser_download_url')

          if [ -z "$TARXZ_URL" ]; then
            echo "Error: Could not find x64 tar.xz release package"
            exit 1
          fi

          TARXZ_SHA256=$(curl -sL $TARXZ_URL | sha256sum | cut -d ' ' -f 1)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "TARXZ_URL=$TARXZ_URL" >> $GITHUB_ENV
          echo "TARXZ_SHA256=$TARXZ_SHA256" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "original_url=$ORIGINAL_URL" >> $GITHUB_OUTPUT
          echo "Downloaded latest x64 release: $VERSION"
          echo "URL: $TARXZ_URL"
          echo "SHA256: $TARXZ_SHA256"

      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod a+x /usr/local/bin/yq

      - name: Update manifest
        run: |
          yq -i '.modules[] | select(.name == "XMCL").sources[0].url = strenv(TARXZ_URL)' io.github.voxelum.xmcl/io.github.voxelum.XMCL.yaml
          yq -i '.modules[] | select(.name == "XMCL").sources[0].sha256 = strenv(TARXZ_SHA256)' io.github.voxelum.xmcl/io.github.voxelum.XMCL.yaml

      - name: Show manifest file before build
        run: |
          echo "Manifest file content:"
          cat io.github.voxelum.xmcl/io.github.voxelum.XMCL.yaml
          echo "File size:"
          ls -lh io.github.voxelum.xmcl/io.github.voxelum.XMCL.yaml

      - name: Build Flatpak
        run: |
          mkdir -p xmcl
          flatpak install --user -y flathub org.freedesktop.Platform//23.08 org.freedesktop.Sdk//23.08
          flatpak-builder --user --force-clean --arch=x86_64 build-dir io.github.voxelum.xmcl/io.github.voxelum.XMCL.yaml --repo=XMCL
          flatpak build-bundle XMCL XMCL-${{ env.VERSION }}-x86_64.flatpak io.github.voxelum.XMCL

      - name: Upload Flatpak bundle
        uses: actions/upload-artifact@v4
        with:
          name: XMCL-flatpak-x86_64
          path: XMCL-${{ env.VERSION }}-x86_64.flatpak

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: XMCL-flatpak-x86_64

      - name: Get current date
        id: date
        run: echo "CURRENT_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: v${{ needs.build.outputs.version }} - ${{ env.CURRENT_DATE }}
          tag_name: v${{ needs.build.outputs.version }}
          body: |
            Flatpak build of XMCL v${{ needs.build.outputs.version }}

            Source: ${{ needs.build.outputs.original_url }}
          draft: false
          make_latest: true
          files: |
            XMCL-*-x86_64.flatpak
