name: Build XMCL Flatpak

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder curl wget git xz-utils

      - name: Cache Flatpak dependencies
        id: cache-flatpak
        uses: actions/cache@v4
        with:
          path: |
            ~/.local/share/flatpak
            ~/.cache/flatpak
          key: flatpak-deps-${{ runner.os }}-${{ hashFiles('app.xmcl.voxelum.yaml') }}

      - name: Setup Flatpak remote
        if: steps.cache-flatpak.outputs.cache-hit != 'true'
        run: flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

      - name: Build Flatpak
        run: |
          mkdir -p build-dir
          flatpak install --user -y flathub org.freedesktop.Platform//24.08 org.freedesktop.Sdk//24.08
          flatpak-builder --user --force-clean --arch=x86_64 build-dir app.xmcl.voxelum.yaml --repo=xmcl
          flatpak build-bundle xmcl XMCL-flatpak-x86_64.flatpak app.xmcl.voxelum

      - name: Upload Flatpak bundle
        uses: actions/upload-artifact@v4
        with:
          name: XMCL-flatpak-x86_64
          path: XMCL-flatpak-x86_64.flatpak
