name: Build XMCL Flatpak

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.latest-release.outputs.version }}
      original_url: ${{ steps.latest-release.outputs.original_url }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Flatpak
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder
          flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

      - name: Get latest XMCL release
        id: latest-release
        run: |
          RELEASE_INFO=$(curl -s https://api.github.com/repos/Voxelum/x-minecraft-launcher/releases/latest)
          VERSION=$(echo $RELEASE_INFO | jq -r '.tag_name' | sed 's/^v//')
          ORIGINAL_URL=$(echo $RELEASE_INFO | jq -r '.html_url')
          DEB_URL=$(echo $RELEASE_INFO | jq -r '.assets[] | select(.name | endswith("-amd64.deb")) | .browser_download_url')

          if [ -z "$DEB_URL" ]; then
            echo "Error: Could not find x86_64 (amd64) release package"
            exit 1
          fi

          DEB_SHA256=$(curl -sL $DEB_URL | sha256sum | cut -d ' ' -f 1)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "DEB_URL=$DEB_URL" >> $GITHUB_ENV
          echo "DEB_SHA256=$DEB_SHA256" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "original_url=$ORIGINAL_URL" >> $GITHUB_OUTPUT
          echo "Downloaded latest x86_64 release: $VERSION"
          echo "URL: $DEB_URL"
          echo "SHA256: $DEB_SHA256"

      - name: Update manifest
        run: |
          jq --arg url "$DEB_URL" \
             --arg sha "$DEB_SHA256" \
             'reduce paths(objects | select(.name? == "xmcl" and .sources)) as $p (.;
               setpath($p + ["sources", 0, "url"]; $url) |
               setpath($p + ["sources", 0, "sha256"]; $sha) |
               setpath($p + ["sources", 0, "dest-filename"]; "xmcl.deb"))' \
               io.github.voxelum.xmcl.json > updated.json

          jq '.["build-options"] = {"arch": ["x86_64"]}' updated.json > io.github.voxelum.xmcl.json

      - name: Build Flatpak
        run: |
          mkdir -p xmcl
          flatpak install --user -y flathub org.freedesktop.Platform//23.08 org.freedesktop.Sdk//23.08
          flatpak-builder --user --force-clean --arch=x86_64 build-dir io.github.voxelum.xmcl.json --repo=xmcl
          flatpak build-bundle xmcl xmcl-${{ env.VERSION }}-x86_64.flatpak io.github.voxelum.xmcl

      - name: Upload Flatpak bundle
        uses: actions/upload-artifact@v4
        with:
          name: xmcl-flatpak-x86_64
          path: xmcl-${{ env.VERSION }}-x86_64.flatpak

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: xmcl-flatpak-x86_64

      - name: Get current date
        id: date
        run: echo "CURRENT_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: v${{ needs.build.outputs.version }} - ${{ env.CURRENT_DATE }}
          tag_name: v${{ needs.build.outputs.version }}
          body: |
            Flatpak build of XMCL v${{ needs.build.outputs.version }}

            Source: ${{ needs.build.outputs.original_url }}
          draft: false
          make_latest: true
          files: |
            xmcl-*-x86_64.flatpak
